### ISSUE TITLE
Issue Stream for Multitargeting Window

### ISSUE THREAD

**Issue by bdoze90** [TrinhLab/CASPERapp#10]
First List:
-Increase length of the Qcombobox for Organism and Seed ID
-Increase length of Qlabel for Seed ID so it does not get truncated
-remove the "." from the end of all the endonucleases (my guess is a substring off by 1 error)
-Make Analyze button a tiny bit bigger so that it can be seen in completeness
-Check statistics overview window to make sure all the labels are big enough to contain the text that goes to them

**Comment by TannerFry** [comment]
All the above issues have been tweaked / fixed and are ready to be reviewed
