### ISSUE TITLE
Multitargeting Table Bug When Switching Organisms

### ISSUE THREAD

**Issue by ddooley2** [TrinhLab/CASPERapp#115]
Errors that occur after analyzing the initial organism:

- Changing organism selection and clicking "Analyze" while table row is still highlighted results in crash:
![image](https://user-images.githubusercontent.com/52081023/119021715-bee22e80-b96d-11eb-8c1a-81ceca2609d3.png)
- Changing organism (but not clicking "Analyze") and trying to highlight a row in the table results in crash after clicking OK on the popup dialog box:
![image](https://user-images.githubusercontent.com/52081023/119022045-27c9a680-b96e-11eb-9758-21907c4b9e55.png)
![image](https://user-images.githubusercontent.com/52081023/119022071-3021e180-b96e-11eb-936d-2ea36e882cd2.png)

**Comment by TannerFry** [comment]
Fixed
