### ISSUE TITLE
Cotargeting on results window

### ISSUE THREAD

**Issue by bdoze90** [TrinhLab/CASPERapp#12]
Somewhat short issue to resolve.  There should be an option for the user to display targets for multiple endonucleases.  This should work with a tool in the dropdown menu that says "Enable Cotargeting" which will display a list of endonuclease sets available.  There will eventually be a section for the user to define a new set but not right now.  The user can select their set and then that gets appended to the list on the combobox which then when selected pulls up targets that are shared between the endonucleases in the list.  I will demonstrate an example when we get to this code and can scan the drawing and upload it here.

**Comment by jherman1997** [comment]
I have begun on the CoTargeting enhancement.

The window has been created and works. We just need to figure out how to work with the Results table now. Working something out on paper first, then will speak to Brian about it

**Comment by jherman1997** [comment]
Cotargeting is mostly done. Just need to go back and add in the PAM direction once that functionality is put in
