### ISSUE TITLE
Select All checkbox in View Targets Window Crashes Program on Mac

### ISSUE THREAD

**Issue by ddooley2** [TrinhLab/CASPERapp#35]
Organism: Arabidopsis thaliana
Cas: asCas12
Annotation: Kegg
OS: Mac
Gene search: adhE

screenshots below.

Location in GUI of error:
![image](https://user-images.githubusercontent.com/52081023/90426448-16760580-e08f-11ea-8d16-35caa43d73bf.png)
Error message:
![image](https://user-images.githubusercontent.com/52081023/90426512-2db4f300-e08f-11ea-8060-71afaebd4236.png)

**Comment by TannerFry** [comment]
Closing this issue since we pulled out the Kegg functionality.
