### ISSUE TITLE
Renaming Annotation Files

### ISSUE THREAD

**Issue by ddooley2** [TrinhLab/CASPERapp#43]
It's confusing trying to keep track of which downloaded annotation file corresponds to which organism. To account for this, we can just rename the annotation file once it's downloaded to _speciesname___strainname__.ext

**Comment by TannerFry** [comment]
Added in the functionality to rename annotation files in the NCBI tool. Now, once the files are downloaded and decompressed, the user is prompted with the option to rename the files. The user does not need to include file extensions but they can if they want. Any rename fields left blank will just keep the original filename.
