### ISSUE TITLE
Update CSPR File Parsing Function

### ISSUE THREAD

**Issue by ddooley2** [TrinhLab/CASPERapp#67]
The way files are pulled into Main Window, MT, and PA is currently incapable of separating CSPR files of the same species but different strain. Also, the current parsing function prevents having underscores in the organism code. To fix this, change parsing logic to jump to ".cspr" in file name and split necessary info out from back to front. CSPR file population can be based off of unique organism codes in filenames and not name within the file.

**Comment by TannerFry** [comment]
File name parsing has been updated in main, results, mt, and pop
