### ISSUE TITLE
Colormap Graph Normalization in Pop. Analysis

### ISSUE THREAD

**Issue by ddooley2** [TrinhLab/CASPERapp#69]
Currently the color bar is scaled from min to max of data set, which can skew colors overwhelmingly to one organism with lots of self repeats. Instead, scale color bar from 0 to max of non-self repeats in data set and set all self repeats to max value color (if possible). If this is not possible, just scale from 0 to max of all repeats.

**Comment by TannerFry** [comment]
Fixed
