### ISSUE TITLE
Gene Viewer feature in Results window

### ISSUE THREAD

**Issue by bdoze90** [TrinhLab/CASPERapp#8]
The Gene Viewer window should display the actual DNA sequence of the gene in question, and highlight the target when the target is selected in the table.
Details of Feature:
-This should be toggled dynamically such that selecting and deselecting a target in the table will highlight and unhighlight the sequence.
-There should be a different color for the reverse complement of the sequence and the normal (e.g. red and green)
-The actual DNA sequence can be obtained from a fasta or genbank file, or from KEGG.  If none of the following exist then this feature will return an error saying there is no available reference sequence.
-The start and end lineEdit objects will display the start and end numbers that are passed into the Results window object from the tuple for each gene.  These will switch based on the gene selected in the dropdown menu and any changes to the numbers for each gene should be stored such that if the user toggles between genes the indices that they were using previously are returned here.

**Comment by bdoze90** [comment]
Note on obtaining the sequence: Just use a reference .fna file (same one that is used for generating the .cspr file) for now.  You can store the information about what .fna file name belongs to what organism in the CASPERinfo file if you need to.

**Comment by jherman1997** [comment]
Gene Viewer now works with the Kegg database (except for changing the start/end).
Before I go on to work on the rest of it, I'm going to get the other selections of Annotation Files working first. That way I know how it is organized.

**Comment by jherman1997** [comment]
With my latest push, most of the gene viewer works. 
User can use a GBFF, FNA, or KEGG for the gene viewer sequence.
User can change indices (start/end) for all types of files used. 

I am not closing this issue yet because:
The highlighter is not quite working yet, but because the sequence length and PAM length are not always correct, I cannot tell if that is an issue with my code yet. Once that is fixed, I will be able to change my code accordingly (highlighting issue and/or indexing issue).

**Comment by jherman1997** [comment]
With my latest push, gene viewer pretty much works entirely.

Only reason I am not closing is because there are a few edge cases. Will talk about them in the meeting on Friday.

**Comment by jherman1997** [comment]
Finished the implementation. Waiting on Brian's testing before closing the issue.
